import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AppProvider from "@/components/AppProvider";
import Layout from "@/components/layout";
import NProgressBar from "@/components/NProgressBar";
import "react-notion-x/src/styles.css";
import "prismjs/themes/prism-tomorrow.css";
import "nprogress/nprogress.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notion Blog",
  description: "Generated by create next app&Notion API",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          type="application/rss+xml"
          href="/rss.xml"
          title="Dan DevLog Feed RSS"
        />
      </head>
      <body className={inter.className}>
        <AppProvider>
          <NProgressBar />
          <Layout>{children}</Layout>
        </AppProvider>
      </body>
    </html>
  );
}
